services:
  audio-embeddings:
    image: audio-embedding:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data2wav_in:/input
      - ./data2wav_out:/output
    pull_policy: never
    command: [ "sleep", "infinity"]



